### PR TITLE
preflight before start operation

### LINKED ISSUE #184: Provide "Preflight checks" to Ignite
Before trying to run a VM, make sure that we have a set of dependencies on the host, e.g. `/dev/kvm` available. Otherwise, fail fast. This would pretty much mimic the [kubeadm preflight checks](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go) on an abstract level.

### PR DESCRIPTION
**Pull request by najeal**
This adds preflight checks before start operation.

Fixes #184

### CODE REVIEW

File: pkg/preflight/checks.go [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+
+func (efc ExistingFileChecker) Name() string {
+	return fmt.Sprintf("ExistingFile-%s", strings.Replace(efc.filePath, oldPathString, newPathString, noReplaceLimit))
+}
+
+func (efc ExistingFileChecker) Type() string {
+	return "ExistingFile"
+}
+
+type AvailablePathChecker struct {
```
Comment (luxas) [inline pkg/preflight/checks.go]: this seems unused?

File: pkg/preflight/checks.go [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+func StartCmdChecks(vm *api.VM, ignoredPreflightErrors sets.String) error {
+	checks := []Checker{}
+	kernelUID, err := lookup.KernelUIDForVM(vm, providers.Client)
+	if err != nil {
+		return err
+	}
+	vmDir := filepath.Join(constants.VM_DIR, vm.GetUID().String())
+	kernelDir := filepath.Join(constants.KERNEL_DIR, kernelUID.String())
+	log.Println(vm.GetUID().String())
+	checks = append(checks, ExistingFileChecker{filePath: path.Join(vmDir, constants.METADATA)})
```
Comment (luxas) [inline pkg/preflight/checks.go]: No need to check for the metadata and kernel files, they are gonna be created on the fly.

File: pkg/preflight/checks.go [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+
+func StartCmdChecks(vm *api.VM, ignoredPreflightErrors sets.String) error {
+	checks := []Checker{}
+	kernelUID, err := lookup.KernelUIDForVM(vm, providers.Client)
+	if err != nil {
+		return err
+	}
+	vmDir := filepath.Join(constants.VM_DIR, vm.GetUID().String())
+	kernelDir := filepath.Join(constants.KERNEL_DIR, kernelUID.String())
+	log.Println(vm.GetUID().String())
```
Comment (luxas) [inline pkg/preflight/checks.go]: remove this?

File: pkg/preflight/checks.go [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+	checks = append(checks, ExistingFileChecker{filePath: path.Join(vmDir, constants.METADATA)})
+	checks = append(checks, ExistingFileChecker{filePath: path.Join(kernelDir, constants.KERNEL_FILE)})
+	checks = append(checks, ExistingFileChecker{filePath: "/dev/mapper/control"})
+	checks = append(checks, ExistingFileChecker{filePath: "/dev/net/tun"})
+	checks = append(checks, ExistingFileChecker{filePath: "/dev/kvm"})
+	for _, port := range vm.Spec.Network.Ports {
+		checks = append(checks, PortOpenChecker{port: port.HostPort})
+	}
+	return runChecks(checks, ignoredPreflightErrors)
```
Comment (luxas) [inline pkg/preflight/checks.go]: other things that could be added:
 - make sure that the docker/containerd socket exists?
   - this could be done by extending `runtime.Interface` with a `PreflightChecker() preflight.Checker` method. when invoked, it would make sure docker / containerd sockets exist
   - here in this method you'd do `checks = append(checks, providers.Runtime.PreflightChecker())`
 - make sure all the binaries listed in https://ignite.readthedocs.io/en/stable/dependencies.html are present in PATH

File: pkg/preflight/checkers/checks.go [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+import (
+	"bytes"
+	"fmt"
+	"net"
+	"os"
+	"os/exec"
+	"strings"
+
+	"k8s.io/apimachinery/pkg/util/sets"
+
```
Comment (twelho) [inline pkg/preflight/checkers/checks.go]: Remove this newline

File: pkg/preflight/checkers/checks.go [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+type AvailablePathChecker struct {
+	path string
+}
+
+func StartCmdChecks(vm *api.VM, ignoredPreflightErrors sets.String) error {
+	checks := []Checker{}
+	checks = append(checks, ExistingFileChecker{filePath: "/dev/mapper/control"})
+	checks = append(checks, ExistingFileChecker{filePath: "/dev/net/tun"})
+	checks = append(checks, ExistingFileChecker{filePath: "/dev/kvm"})
+	checks = append(checks, providers.Runtime.PreflightChecker())
```
Comment (twelho) [inline pkg/preflight/checkers/checks.go]: This could be an inline constructor instead of 4 allocations

**Comment by najeal** [comment]
Done.
I can squash if needed

File: pkg/preflight/checkers/checks.go (hunk 6 above)
Comment (chanwit) [reply pkg/preflight/checkers/checks.go]: @najeal could you please address this per @twelho comment.

**Comment by chanwit** [comment]
This preflight would be a life saver, thank you @najeal !!

It seems that we have some changes since last time, like
  * `containerd` detection
  * `git` should be optionally detected.
But I think this could be addressed by another PR.

Small things left to be addressed. /cc @stealthybox
